language: cpp

compiler:
  - gcc

os:
  - linux

sudo: false
cache:
  apt: true

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^.*travis.*$/

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  - source .travis/${TRAVIS_OS_NAME}/before_install.sh

before_script:
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build . --target all -- --keep-going
  - cmake --build . --target check
